### ISSUE TITLE
ChromeDriver version not found

### ISSUE THREAD

**Issue by chris-iwolf** [ilkerogutcu/keydrop-giveaway-bot#11]
Hello,

I followed your instruction, set the session_id and the user_agent and build then run but I got this error.
Please help:

```
[23-11-02 21:05:16 INF] Starting KeyDrop Giveaway Bot
[23-11-02 21:05:16 INF] Setting KeyDrop cookie...
Unhandled exception. System.Exception: ChromeDriver version not found for Chrome version 118.0.5993
   at SeleniumUndetectedChromeDriver.ChromeDriverInstaller.Install(String version, Boolean force)
   at SeleniumUndetectedChromeDriver.ChromeDriverInstaller.Auto(String browserExecutablePath, Boolean force)
   at KeyDropGiveawayBot.Services.SessionService.GetCloudFlareCookieValueAsync() in C:\Users\Admin\Desktop\Jett\keydrop-giveaway-bot\src\Services\SessionService.cs:line 73
   at KeyDropGiveawayBot.Services.SessionService.SetKeyDropCookieAsync(CancellationToken cancellationToken) in C:\Users\Admin\Desktop\Jett\keydrop-giveaway-bot\src\Services\SessionService.cs:line 25
   at Program.<Main>$(String[] args) in C:\Users\Admin\Desktop\Jett\keydrop-giveaway-bot\src\Program.cs:line 62
   at Program.<Main>(String[] args)
```

**Comment by wgaabe** [comment]
solved ?
